name: CI
on:
  push:
    branches-ignore: ['all-contributors/**']
  pull_request:
    branches-ignore: ['all-contributors/**']
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: â¬‡ï¸ Checkout repo
        uses: actions/checkout@v4
      - name: â™»ï¸ Cache node_modules
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ hashFiles('package.json') }}
      - name: ğŸ“¥ Install deps
        run: yarn
        env:
          HUSKY_SKIP_INSTALL: true

      - name: âœ Lint
        run: npm run lint
      - name: ğŸ§ª Test
        run: npm run test -- --coverage
      - name: ğŸš§ Build test environments
        run: npm run setup:env
      - name: ğŸ”¬ Test with toolbox
        run: npm run test:toolbox
      - name: ğŸ— Build
        run: npm run build

      - name: â˜‚ï¸ Upload coverage report
        uses: codecov/codecov-action@v5
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  release:
    needs: validate
    runs-on: ubuntu-latest
    if:
      ${{ github.repository == 'testing-library/user-event' &&
      contains('refs/heads/main,refs/heads/beta,refs/heads/alpha', github.ref)
      && github.event_name == 'push' }}
    steps:
      - name: â¬‡ï¸ Checkout repo
        uses: actions/checkout@v4
      - name: â™»ï¸ Restore node_modules
        uses: actions/cache/restore@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ hashFiles('package.json') }}
      - name: ğŸ“¥ Install deps
        run: yarn
        env:
          HUSKY_SKIP_INSTALL: true

      - name: ğŸ—ï¸ Run build script
        run: npm run build

      - name: ğŸš€ Release
        uses: ph-fritsche/action-release@v2
        with:
          dry: ${{ vars.RELEASE_DRY }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
